version: "{build}"

environment:
  nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - npm install

test_script:
  - npm run specs

build: off
